### ISSUE TITLE
Weird Exception coming from Sentry

### ISSUE THREAD

**Issue by pesseyjulien** [getsentry/sentry-symfony#135]
Hi, 

I'm getting this following error which I do not understand :

` Cannot access protected property Raven_ErrorHandler::$error_types in /home/ec2-user/www/api-football/releases/29052018-013805/vendor/sentry/sentry/lib/Raven/ErrorHandler.php:109`

Full log :
```
ErrorException: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Cannot access protected property Raven_ErrorHandler::$error_types in /home/ec2-user/www/api-football/releases/29052018-013805/vendor/sentry/sentry/lib/Raven/ErrorHandler.php:109
Stack trace:
#0 [internal function]: Raven_ErrorHandler->handleError(8, 'Undefined prope...', '/home/ec2-user/...', 629, Array)
#1 /home/ec2-user/www/api-football/releases/29052018-013805/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php(629): ReflectionProperty->getValue(Object(Addict\Bundle\FeedBundle\Document\Categorie))
#2 /home/ec2-user/www/api-football/releases/29052018-013805/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php(702): Doctrine\ODM\MongoDB\UnitOfWork->getDocumentActualData(Object(Addict\Bundle\FeedBundle\Document\Categorie))
#3 /home/ec2-user/www/api-football/releases/29052018-013805/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php(689): Doctrine\ODM\MongoDB\UnitOfWork->computeOrRecomputeChangeSet(O
#1 vendor/sentry/sentry/lib/Raven/ErrorHandler.php(109): handleFatalError
#0 vendor/sentry/sentry/lib/Raven/ErrorHandler.php(0): null
```

Thanks in advance for your help,
Julien

**Comment by Jean85** [comment]
Which version of the bundle are you using? Which version of the base Sentry client?

**Comment by pesseyjulien** [comment]
Sentry client version : 1.9.0
Sentry symfony bundle version: 2.0.2

This is what I have in my composer :

"sentry/sentry-symfony": "^2.0"

**Comment by Jean85** [comment]
That piece of code belongs to the base Sentry client, not to this bundle; you should report it there: https://github.com/getsentry/sentry-php/issues

BTW your stack class seems a little weird, it has mixed stuff in there...
