### ISSUE TITLE
Sentry not ignoring exceptions 

### ISSUE THREAD

**Issue by miljanbrakocevic** [getsentry/sentry-symfony#764]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

3.5.0

### Steps to reproduce

1. We are using Guzzle client v6.  This is the code from their middleware    `public static function httpErrors()
    {
        return function (callable $handler) {
            return function ($request, array $options) use ($handler) {
                if (empty($options['http_errors'])) {
                    return $handler($request, $options);
                }
                return $handler($request, $options)->then(
                    function (ResponseInterface $response) use ($request) {
                        $code = $response->getStatusCode();
                        if ($code < 400) {
                            return $response;
                        }
                        throw RequestException::create($request, $response);
                    }
                );
            };
        };
    }`
2. In our sentry configuration we ignore this exception   
`Sentry\Integration\IgnoreErrorsIntegration:
        arguments:
            $options:
                ignore_exceptions:
                    - GuzzleHttp\Exception\ClientException
                    - GuzzleHttp\Exception\RequestException
 `                   
3.  Exception still logged to our sentry #0 /var/www/our-project/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /var/www/our-project/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))

### Expected result

RequestException from guzzle not logged to sentry

### Actual result

Exception logged to sentry
 #0 /var/www/our-project/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /var/www/our-project/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
```[tasklist]
### Tasks
```

**Comment by miljanbrakocevic** [comment]
Im closing this issue, as it happened the issue was on our side sorry
